# q2.rq
# For each director that has directed actors to win Academy Awards (Oscars), 
# count the number of Academy Award-winning actors (excluding themselves) in their 
# films and count how many Academy Awards these actors have won for the movies 
# directed by the relevant directors. Order by the latter value (number of Academy 
# Awards won).

BASE            <https://en.wikipedia.org/wiki/>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hw:      <http://www.hollywood.com/>
PREFIX date:    <https://timeanddate.com/>
PREFIX dbpedia: <https://dbpedia.org/ontology/>

SELECT ?director (COUNT(?actor) AS ?oscarWinningActors) (COUNT(?award) AS ?numOscarsWon)
WHERE {
    ?director hw:directed ?film .
    ?film hw:casted ?actor .
    ?actor hw:won ?award .
    ?award rdf:type <Academy_Award> .

    FILTER (?director != ?actor)
    FILTER EXISTS { ?award hw:awardedFor ?film }
    FILTER NOT EXISTS { ?award hw:awardedTo ?director }
}
GROUP BY ?director
ORDER BY DESC(?numOscarsWon)